name: Generate Changelog

on:
  push:
    branches:
      - "main"

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate Changelog
        uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: "${{ github.repository }}"
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATH: "docs/CHANGELOG.md" # Adjust the path based on your Docsify project structure
          COMMIT_MESSAGE: "docs(CHANGELOG): update release notes"
          TYPE: "[add]: Feature,[fix]: Bug Fixes,[update]: Documentation"
