name: Generate Changelog

on:
  push:
    branches:
      - "main"

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout
      - name: Generate Changelog
        uses: BobAnkh/auto-generate-changelog@1.2.5
        with:
          REPO_NAME: "${{ github.repository }}"
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATH: "../CHANGELOG" # Adjust the path if needed
          COMMIT_MESSAGE: "docs(CHANGELOG): update release notes"
          TYPE: "[add]: Feature,[fix]: Bug Fixes,[update]: Documentation"
