name: "Release"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false # Change this line to set it to false for an actual release
          title: "Release"
          files: |
            *.json
            pages/*.md
